# Generated by Django 4.2 on 2023-07-22 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AWAITING_PICKUP', 'Przyjęta do recepcji'), ('READY', 'Gotowa do odbioru'), ('SENT', 'Odebrana przez kuriera')], default='AWAITING_PICKUP', max_length=15, verbose_name='Status')),
                ('tracking_number', models.CharField(max_length=255, unique=True, verbose_name='Numer do śledzenia')),
                ('received_at', models.DateTimeField(null=True, verbose_name='Data przyjęcia')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='Data nadania')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Klient', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pracownik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
