# Generated by Django 4.2 on 2023-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='company',
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('PICKUP', 'Odbiór'), ('DELIVERY', 'Wysyłka')], default='PICKUP', max_length=15, verbose_name='Rodzaj przesyłki'),
        ),
    ]
