# Generated by Django 4.2 on 2023-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('AWAITING_PICKUP', 'Przyjęta do recepcji'), ('RECEIVED', 'Odebrana przez klienta'), ('READY', 'Gotowa do odbioru'), ('SENT', 'Wydana kurierowi')], default='AWAITING_PICKUP', max_length=15, verbose_name='Status'),
        ),
    ]
