# Generated by Django 4.2 on 2023-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_orderitem_product_delete_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Oczekuje na realizację'), ('done', 'Zamówienie zostało zrealizowane')], default='new', max_length=32, verbose_name='Status'),
        ),
    ]
