# Generated by Django 4.2 on 2023-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_order_is_confirmed_order_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
