# Generated by Django 4.2 on 2023-08-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
    ]
