# Generated by Django 4.2 on 2023-08-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
