# Generated by Django 4.2 on 2023-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='businessArea',
            field=models.CharField(choices=[('design', 'Design'), ('it', 'IT'), ('co-working', 'Co-working'), ('real estate', 'Real estate'), ('customer service', 'Customer service'), ('data analysis', 'Data analysis'), ('programing', 'Programing'), ('marketing', 'Marketing'), ('financed', 'Financed'), ('insurance', 'Insurance'), ('architecture', 'Architecture')], default='customer service', max_length=32, verbose_name='Business area'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=256, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(max_length=20, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipCode',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
    ]
