# Generated by Django 4.2 on 2023-06-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_businessarea_alter_company_companyname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
    ]
