# Generated by Django 4.2 on 2023-08-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firma'},
        ),
    ]
