# Generated by Django 4.2 on 2023-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='businessArea',
            field=models.CharField(choices=[('design', 'Design'), ('it', 'IT'), ('co-working', 'Co-working'), ('real estate', 'Real estate'), ('customer service', 'Customer service'), ('data analysis', 'Data analysis'), ('programing', 'Programing'), ('marketing', 'Marketing'), ('financed', 'Financed'), ('insurance', 'Insurance'), ('architecture', 'Architecture')], default='customer service', max_length=32, verbose_name='Obszar Działalności'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=256, verbose_name='Nazwa Firmy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipCode',
            field=models.CharField(max_length=10, verbose_name='Kod Pocztowy'),
        ),
    ]
