# Generated by Django 4.2 on 2023-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_businessarea_alter_company_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='businessArea',
            field=models.CharField(choices=[('design', 'Projektowanie'), ('it', 'IT'), ('co-working', 'Współpraca'), ('real estate', 'Nieruchomości'), ('customer service', 'Obsługa klienta'), ('data analysis', 'Analiza danych'), ('programing', 'Programowanie'), ('marketing', 'Marketing'), ('financed', 'Finanse'), ('insurance', 'Ubezpieczenia'), ('architecture', 'Architektura')], default='customer service', max_length=32, verbose_name='Obszar Działalności'),
        ),
    ]
