# Generated by Django 4.2 on 2023-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_businessarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Firma'},
        ),
    ]
