# Generated by Django 4.2 on 2023-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('I', 'Piętro I'), ('II', 'Piętro II'), ('III', 'Piętro III'), ('IV', 'Piętro VI'), ('V', 'Piętro V'), ('VI', 'Piętro VI'), ('VII', 'Piętro VII')], default='I', max_length=32, verbose_name='Floor'),
        ),
    ]
