# Generated by Django 4.2 on 2023-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='destination',
            field=models.CharField(choices=[('office', 'Biuro'), ('conference_room', 'Sala Konferencyjna')], default='office', max_length=32, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Cena'),
            preserve_default=False,
        ),
    ]
