# Generated by Django 4.2 on 2023-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_roomreservation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='cost',
            field=models.IntegerField(default=50, verbose_name='Koszt'),
            preserve_default=False,
        ),
    ]
