# Generated by Django 4.2 on 2023-08-15 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0009_officeroomreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('model', models.CharField(choices=[('HP_LaserJet', 'HP LaserJet Pro M404n'), ('Canon_PIXMA', 'Canon PIXMA TR4520'), ('Epson_WorkForce', 'Epson WorkForce WF-2830'), ('Brother_HL', 'Brother HL-L2300D'), ('Samsung_M2020', 'Samsung Xpress M2020W'), ('Lexmark_C3224', 'Lexmark C3224dw'), ('Dell_E310', 'Dell E310DW')], default='HP_LaserJet', max_length=32, verbose_name='Destination')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('I', 'Piętro I'), ('II', 'Piętro II'), ('III', 'Piętro III'), ('IV', 'Piętro IV'), ('V', 'Piętro V'), ('VI', 'Piętro VI'), ('VII', 'Piętro VII')], default='I', max_length=32, verbose_name='Floor'),
        ),
        migrations.CreateModel(
            name='PrinterRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('cost', models.IntegerField(verbose_name='Koszt')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.printers')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
