# Generated by Django 4.2 on 2023-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_printers_alter_room_location_printerrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='model',
            field=models.CharField(choices=[('HP_LaserJet', 'HP LaserJet Pro M404n'), ('Canon_PIXMA', 'Canon PIXMA TR4520'), ('Epson_WorkForce', 'Epson WorkForce WF-2830'), ('Brother_HL', 'Brother HL-L2300D'), ('Samsung_M2020', 'Samsung Xpress M2020W'), ('Lexmark_C3224', 'Lexmark C3224dw'), ('Dell_E310', 'Dell E310DW')], default='HP_LaserJet', max_length=32, verbose_name='Model'),
        ),
    ]
