# Generated by Django 4.2 on 2023-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_printers_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='number_of_page',
            field=models.IntegerField(default=0, verbose_name='Liczba Stron'),
        ),
    ]
