# Generated by Django 4.2 on 2023-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_printers_number_of_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='date_of_last_service',
            field=models.DateField(null=True, verbose_name='Data Ostaniego Serwisu'),
        ),
        migrations.AddField(
            model_name='printers',
            name='date_of_next_service',
            field=models.DateField(null=True, verbose_name='Data Następnego Serwisu'),
        ),
    ]
