# Generated by Django 4.2 on 2023-08-16 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_printers_date_of_last_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='date_of_last_service',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Ostaniego Serwisu'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='date_of_next_service',
            field=models.DateField(default=datetime.date(2024, 2, 14), verbose_name='Data Następnego Serwisu'),
        ),
    ]
