# Generated by Django 4.2 on 2023-08-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_alter_printers_date_of_last_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='date_of_last_service',
            field=models.DateField(null=True, verbose_name='Data Ostaniego Serwisu'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='date_of_next_service',
            field=models.DateField(null=True, verbose_name='Data Następnego Serwisu'),
        ),
    ]
