# Generated by Django 4.2 on 2023-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_printers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='status',
            field=models.CharField(choices=[('in_use', 'W Użyciu'), ('service', 'Na Serwisie'), ('unused', 'Nie używana')], default='unused', max_length=32, verbose_name='Status'),
        ),
    ]
