# Generated by Django 4.2 on 2023-08-16 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_alter_printers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printers',
            name='number_of_page',
        ),
        migrations.AddField(
            model_name='printerrent',
            name='number_of_page',
            field=models.CharField(choices=[('100', '100'), ('250', '250'), ('500', '500'), ('100', '1000+')], default='100', max_length=32, verbose_name='liczba Stron'),
        ),
        migrations.AlterField(
            model_name='printerrent',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data rozpoczęcia'),
        ),
    ]
