# Generated by Django 4.2 on 2023-08-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_remove_printers_number_of_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerrent',
            name='room',
        ),
    ]
