# Generated by Django 4.2 on 2023-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_remove_printerrent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='serial_number',
            field=models.IntegerField(default=0, verbose_name='Numer Seryjny'),
            preserve_default=False,
        ),
    ]
