# Generated by Django 4.2 on 2023-08-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_printers_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='serial_number',
            field=models.CharField(max_length=200, verbose_name='Numer Seryjny'),
        ),
    ]
