# Generated by Django 4.2 on 2023-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_alter_printers_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeroomreservation',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='printerrent',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rabat'),
        ),
    ]
