# Generated by Django 4.2 on 2023-08-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_alter_company_businessarea_alter_company_companyname_and_more'),
        ('reservation', '0022_officeroomreservation_discount_printerrent_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeroomreservation',
            options={'verbose_name': 'Biura', 'verbose_name_plural': 'Biura'},
        ),
        migrations.AlterModelOptions(
            name='printerrent',
            options={'verbose_name': 'Wynajem Drukarek', 'verbose_name_plural': 'Wynajem Drukarek'},
        ),
        migrations.AlterModelOptions(
            name='printers',
            options={'verbose_name': 'Drukarki', 'verbose_name_plural': 'Drukarki'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Pomieszczenia', 'verbose_name_plural': 'Pomieszczenia'},
        ),
        migrations.AlterModelOptions(
            name='roomreservation',
            options={'verbose_name': 'Sale Konferencyjne', 'verbose_name_plural': 'Sale Konferencyjne'},
        ),
        migrations.AlterField(
            model_name='officeroomreservation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='officeroomreservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Pomieszczenie'),
        ),
        migrations.AlterField(
            model_name='officeroomreservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='printerrent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='printerrent',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.printers', verbose_name='Drukarka'),
        ),
        migrations.AlterField(
            model_name='printerrent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='room',
            name='destination',
            field=models.CharField(choices=[('office', 'Biuro'), ('conference_room', 'Sala Konferencyjna')], default='office', max_length=32, verbose_name='Przeznaczenie'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('I', 'Piętro I'), ('II', 'Piętro II'), ('III', 'Piętro III'), ('IV', 'Piętro IV'), ('V', 'Piętro V'), ('VI', 'Piętro VI'), ('VII', 'Piętro VII')], default='I', max_length=32, verbose_name='Piętro'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='end_time',
            field=models.TimeField(verbose_name='Data Zakończenia'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Pomieszczenie'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='start_time',
            field=models.TimeField(verbose_name='Data Rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
