# Generated by Django 4.2 on 2023-08-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_alter_officeroomreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeroomreservation',
            options={'verbose_name': 'Biura', 'verbose_name_plural': 'Biura'},
        ),
        migrations.AlterModelOptions(
            name='printerrent',
            options={'verbose_name': 'Wynajem Drukarek', 'verbose_name_plural': 'Wynajem Drukarek'},
        ),
        migrations.AlterModelOptions(
            name='printers',
            options={'verbose_name': 'Drukarki', 'verbose_name_plural': 'Drukarki'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Pomieszczenia', 'verbose_name_plural': 'Pomieszczenia'},
        ),
        migrations.AlterModelOptions(
            name='roomreservation',
            options={'verbose_name': 'Sale Konferencyjne', 'verbose_name_plural': 'Sale Konferencyjne'},
        ),
    ]
