# Generated by Django 4.2 on 2023-08-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_alter_officeroomreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeroomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Pomieszczenie'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Pomieszczenie'),
        ),
    ]
