# Generated by Django 4.2 on 2023-07-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titile',
            new_name='title',
        ),
    ]
