# Generated by Django 4.2 on 2023-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_titile_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], default='software', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('inProgress', 'In Progess'), ('resolve', 'Resolve')], default='new', max_length=200, verbose_name='Status'),
        ),
    ]
