# Generated by Django 4.2 on 2023-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_category_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='floor',
            field=models.CharField(choices=[('I', 'Piętro I'), ('II', 'Piętro II'), ('III', 'Piętro III'), ('IV', 'Piętro VI'), ('V', 'Piętro V'), ('VI', 'Piętro VI'), ('VII', 'Piętro VII')], default='I', max_length=32, verbose_name='Floor'),
        ),
    ]
