# Generated by Django 4.2 on 2023-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('inProgress', 'In Progess'), ('resolve', 'Resolved')], default='new', max_length=200, verbose_name='Status'),
        ),
    ]
