# Generated by Django 4.2 on 2023-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_ticket_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Godzina zamknięcia zgłoszenia'),
        ),
    ]
