# Generated by Django 4.2 on 2023-08-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_officeroomreservation'),
        ('support', '0012_alter_ticket_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='office',
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.room'),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
