# Generated by Django 4.2 on 2023-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_remove_ticket_office_ticket_room_delete_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='floor',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nowy'), ('inProgress', 'W toku'), ('resolved', 'Rozwiązano')], default='new', max_length=200, verbose_name='Status'),
        ),
    ]
