# Generated by Django 4.2 on 2023-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_remove_ticket_floor_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentarze', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Zgłoszenia', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Zawartość'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Utworzenia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], default='software', max_length=32, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='low', max_length=32, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
    ]
