# Generated by Django 4.2 on 2023-08-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_alter_comment_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Ticket'},
        ),
    ]
