# Generated by Django 4.2 on 2023-08-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_alter_comment_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentarze', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Zgłoszenia', 'verbose_name_plural': 'Zgłoszenia'},
        ),
    ]
