# Generated by Django 4.2 on 2023-08-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_alter_printerrent_company_alter_printerrent_printer_and_more'),
        ('support', '0018_alter_ticket_room_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.room'),
        ),
    ]
