# Generated by Django 4.2 on 2023-06-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('businessArea', models.CharField(choices=[('design', 'Design'), ('it', 'IT'), ('co-working', 'Co-working'), ('real estate', 'Real estate'), ('customer service', 'Customer service'), ('data analysis', 'Data analysis'), ('programing', 'Programing'), ('marketing', 'Marketing'), ('financed', 'Financed'), ('insurance', 'Insurance'), ('architecture', 'Architecture')], default='customer service', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
