# Generated by Django 4.2 on 2023-08-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_person',
            field=models.CharField(choices=[('yes', 'Tak'), ('no', 'Nie')], default='no', max_length=32, verbose_name='Osoba Kontaktowa'),
        ),
    ]
