# Generated by Django 4.2 on 2023-08-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_alter_company_businessarea_alter_company_companyname_and_more'),
        ('account', '0008_account_contact_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konto'},
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(max_length=256, verbose_name='Pozycja'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
