# Generated by Django 4.2 on 2023-08-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_options_alter_account_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Account'},
        ),
    ]
