# Generated by Django 4.2 on 2023-08-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konto'},
        ),
    ]
