# Generated by Django 4.2 on 2023-05-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inz', '0002_auto_20170703_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
