# Generated by Django 4.2 on 2023-06-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inz', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
    ]
