# Generated by Django 4.2 on 2023-06-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_account_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsName', models.CharField(max_length=256, verbose_name='Event Name')),
                ('description', models.CharField(max_length=256, verbose_name='Event Name')),
                ('publicationDate', models.DateTimeField()),
                ('newsCategory', models.CharField(choices=[('about building', 'About Building'), ('building', 'Building')], default='building', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=256, verbose_name='Event Name')),
                ('event_date', models.DateTimeField()),
                ('description', models.CharField(max_length=256, verbose_name='Venue')),
                ('venue', models.CharField(choices=[('imperator', 'Imperator')], default='imperator', max_length=32)),
                ('eventCategory', models.CharField(choices=[('action', 'Actions'), ('building', 'Building'), ('contest', 'Contest'), ('about_the_building', 'About the Building'), ('promotions', 'Promotions'), ('celebration', 'Celebration'), ('events', 'Events'), ('event', 'Event'), ('results', 'Results')], default='event', max_length=32)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
