# Generated by Django 4.2 on 2023-06-22 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventCategory',
            field=models.CharField(choices=[('action', 'Actions'), ('building', 'Building'), ('contest', 'Contest'), ('about_the_building', 'About the Building'), ('promotions', 'Promotions'), ('celebration', 'Celebration'), ('events', 'Events'), ('event', 'Event'), ('results', 'Results')], default='event', max_length=32, verbose_name='Event category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventName',
            field=models.CharField(max_length=256, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(choices=[('imperator', 'Imperator')], default='imperator', max_length=32, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsCategory',
            field=models.CharField(choices=[('about building', 'About Building'), ('building', 'Building')], default='building', max_length=32, verbose_name='News category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsName',
            field=models.CharField(max_length=256, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publicationDate',
            field=models.DateTimeField(verbose_name='Publication date'),
        ),
    ]
