# Generated by Django 4.2 on 2023-06-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_events_description_alter_events_eventcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_date',
            new_name='eventDate',
        ),
        migrations.AddField(
            model_name='news',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
