# Generated by Django 4.2 on 2023-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_description_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Events', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='publicationDate',
            field=models.DateField(verbose_name='Publication date'),
        ),
    ]
