# Generated by Django 4.2 on 2023-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_news_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsName',
            field=models.CharField(max_length=256, verbose_name='News name'),
        ),
    ]
