# Generated by Django 4.2 on 2023-07-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_news_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
