# Generated by Django 4.2 on 2023-07-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_news_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='inz/media/images', verbose_name='Image'),
        ),
    ]
