# Generated by Django 4.2 on 2023-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_news_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventDate',
            field=models.DateField(verbose_name='Event date'),
        ),
    ]
