# Generated by Django 4.2 on 2023-07-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_events_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventImage',
            field=models.ImageField(blank=True, null=True, upload_to='inz/media/images', verbose_name='Image'),
        ),
    ]
