# Generated by Django 4.2 on 2023-07-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_events_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
