# Generated by Django 4.2 on 2023-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_events_eventimage_alter_news_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publicationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Publication Date'),
        ),
    ]
