# Generated by Django 4.2 on 2023-07-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_news_publicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publicationDate',
            field=models.DateField(verbose_name='Publication Date'),
        ),
    ]
