# Generated by Django 4.2 on 2023-07-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_news_publicationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='autor',
            new_name='author',
        ),
    ]
