# Generated by Django 4.2 on 2023-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_autor_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(choices=[('imperator', 'Imperator Kraków')], default='imperator', max_length=32, verbose_name='Venue'),
        ),
    ]
