# Generated by Django 4.2 on 2023-08-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_company_manager'),
        ('events', '0017_alter_events_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=256, verbose_name='Tytuł Oferty')),
                ('publicationDate', models.DateField(verbose_name='Publication Date')),
                ('offer_Image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Zdjęcie')),
                ('descriptiom', models.TextField(verbose_name='Opis Oferty')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'verbose_name': 'Oferty',
                'verbose_name_plural': 'Oferty',
            },
        ),
    ]
