# Generated by Django 4.2 on 2023-08-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_discount_delete_offers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Rabat'},
        ),
    ]
