# Generated by Django 4.2 on 2023-08-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_discount_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
