# Generated by Django 4.2 on 2023-08-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_alter_company_businessarea_alter_company_companyname_and_more'),
        ('events', '0022_delete_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Rabat', 'verbose_name_plural': 'Rabat'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Wydarzenia', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='discount',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='publicationDate',
            field=models.DateField(verbose_name='Data Publikacji'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsCategory',
            field=models.CharField(choices=[('about building', 'O Budynku'), ('building', 'Budynek')], default='building', max_length=32, verbose_name='Kategoria Wydarzenia'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsName',
            field=models.CharField(max_length=256, verbose_name='Nazwa Wydarzenia'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publicationDate',
            field=models.DateField(verbose_name='Data Publikacji'),
        ),
    ]
