# Generated by Django 4.2 on 2023-08-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0011_alter_company_options'),
        ('events', '0025_alter_discount_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Klient'),
        ),
    ]
